/**
 * Turns the Skool export into the data the course pages render.
 *
 *   node scripts/build-course.mjs
 *
 * Reads content/courses/codex-mastery.md — the export exactly as it came out
 * of Skool — and writes lib/courses/codex-mastery.ts. The markdown stays the
 * source of truth: re-export from Skool, drop the file in, run this again.
 *
 * Images are resolved by convention rather than by parsing the prose
 * directives around them. The export writes those directives three different
 * ways ("insert at top of lesson body", "Image order for this lesson", and a
 * "**Module banner:**" line), and a parser that tries to read all three is a
 * parser that breaks on the fourth. The filenames are perfectly regular, so:
 *
 *   codex-lesson-<m>-<n>-*.png   the lesson's own square icon
 *   codex-module-<m>-banner.png  the module banner, shown on lesson <m>.1
 *
 * which is exactly where the export says each one belongs.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import path from "node:path";

const MD = path.join("content", "courses", "codex-mastery.md");
const IMG_DIR = path.join("public", "community", "claudecodexzero");
const OUT = path.join("lib", "courses", "codex-mastery.ts");

const md = readFileSync(MD, "utf8");
const images = readdirSync(IMG_DIR);
const findImage = (prefix) => {
  const hit = images.find((f) => f.startsWith(prefix) && f.endsWith(".png"));
  /* Served from under /community, not /courses. The old /courses address
     redirects its second segment to a lesson, and an image sitting there was
     being redirected to a lesson that does not exist. */
  return hit ? `/community/claudecodexzero/${hit}` : null;
};

const slugify = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");

/* Lines that are directions to whoever is pasting this into a platform, not
   lesson text. They would read as instructions to the student. */
const isDirective = (l) =>
  /^\*\[Image/i.test(l) ||
  /^\*\[Image order/i.test(l) ||
  /^\*\*Module banner:\*\*/i.test(l) ||
  /^\*\*Course cover image:\*\*/i.test(l);

const modules = [];
let mod = null, lesson = null;

for (const raw of md.split("\n")) {
  const line = raw.trimEnd();

  const mHead = line.match(/^##\s+Module\s+(\d+)\s+[—-]\s+(.+?)\s*$/);
  if (mHead) {
    mod = { num: Number(mHead[1]), title: mHead[2], lessons: [] };
    modules.push(mod);
    lesson = null;
    continue;
  }
  /* Anything else at ## level ends the course body — the export finishes with
     a status table aimed at whoever was doing the migration. */
  if (/^##\s+/.test(line) && !mHead) { mod = null; lesson = null; continue; }

  const lHead = line.match(/^###\s+(\d+)\.(\d+)\s+(.+?)\s*$/);
  if (lHead && mod) {
    const [, m, n, title] = lHead;
    lesson = {
      num: `${m}.${n}`,
      title,
      slug: `${m}-${n}-${slugify(title)}`,
      icon: findImage(`codex-lesson-${m}-${n}-`),
      /* The module banner rides on the module's opening lesson, which is
         where the export puts it. */
      banner: n === "1" ? findImage(`codex-module-${m}-banner`) : null,
      body: [],
      task: null,
    };
    mod.lessons.push(lesson);
    continue;
  }

  if (!lesson || !line.trim() || line.trim() === "---") continue;
  if (isDirective(line.trim())) continue;

  /* The closing instruction of nearly every lesson. Pulled out so the page
     can draw it as the thing to go and do, rather than as one more
     paragraph the eye slides off. */
  const task = line.match(/^Do this before moving on:\s*(.+)$/i);
  if (task) { lesson.task = task[1].trim(); continue; }

  lesson.body.push(line.trim());
}

const lessons = modules.flatMap((m) => m.lessons);
if (!modules.length || !lessons.length) {
  console.error("! parsed nothing — the export's heading shape must have changed");
  process.exit(1);
}

const missing = lessons.filter((l) => !l.icon);
const noTask = lessons.filter((l) => !l.task);
console.log(`${modules.length} modules, ${lessons.length} lessons`);
console.log(`  cover        ${findImage("codex-course-cover") ? "found" : "MISSING"}`);
console.log(`  banners      ${modules.filter((m) => m.lessons[0]?.banner).length}/${modules.length}`);
console.log(`  lesson icons ${lessons.length - missing.length}/${lessons.length}`);
if (missing.length) console.log(`   missing icons: ${missing.map((l) => l.num).join(", ")}`);
if (noTask.length) console.log(`  no closing task on ${noTask.map((l) => l.num).join(", ")} (fine, it is optional)`);
const short = lessons.filter((l) => l.body.length < 2);
if (short.length) { console.error(`! lesson(s) with almost no body: ${short.map((l) => l.num).join(", ")}`); process.exit(1); }

const banner = `/* Generated by scripts/content/build-course.mjs from content/courses/codex-mastery.md.
   Do not edit by hand — re-export from Skool and run the script. */`;

const body = `${banner}

export type Lesson = {
  num: string;
  title: string;
  slug: string;
  icon: string | null;
  banner: string | null;
  body: string[];
  task: string | null;
};

export type CourseModule = { num: number; title: string; lessons: Lesson[] };

export type Course = {
  slug: string;
  title: string;
  blurb: string;
  cover: string | null;
  modules: CourseModule[];
};

/* One course. Which community it belongs to is not stated here — a course is
   a thing that can sit in a classroom, and the registry in lib/community
   decides which classroom that is. */
export const COURSE: Course = {
  slug: "codex-mastery",
  title: "Codex Mastery",
  cover: ${JSON.stringify(findImage("codex-course-cover"))},
  blurb:
    "The full Codex course \u2014 five modules, twenty lessons, from your first session to shipping a feature with an agent at the keyboard.",
  modules: ${JSON.stringify(modules, null, 2)},
};
`;

mkdirSync(path.dirname(OUT), { recursive: true });
writeFileSync(OUT, body);
console.log(`\nwrote ${OUT}`);
